name: CI-front

# on: Eventos que hacen triggers del workflow
on:
  pull_request:
    branches: [ main ]
    paths: [ 'code/hangman-front/**' ]
  # Añadimos el caso push
  push:
    branches: [ main ]
    paths: [ 'code/hangman-front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) traemos el código fuente del repo
    - name: Checkout
      uses: actions/checkout@v6
    # 2) Setear la versión de Node
    - name: Setup Node.js version
      uses: actions/setup-node@v6
      with:
        node-version: 18
    # 3) Hacemos el build
    - name: Build
      working-directory: ./code/hangman-api
      run: |
        npm ci
        npm run build --if-present

  test:
    runs-on: ubuntu-22.04
    # Depende del build
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Unit tests
        working-directory: ./code/hangman-api
        run: |
          npm ci
          npm run test
